package com.amt.dto;

import java.util.Objects;

//DTO - Data Transfer Object
// This is to be used in the controller class to get parameters by body
public class AddCustomerDTO {
	private String username = "";
	private String password = "";
	private String firstName = "";
	private String lastName = "";
	private String email = "";

	/*
	 * private int userId = 0; Cannot be set auto generated in the database private
	 * String passwordSalt = ""; Cannot be set is generated by system private
	 * EmployeeRole employeeRole; Customers do not have an employee role, set to
	 * null in processing private UserType userType; Processing sets to Customer
	 */

	public AddCustomerDTO() {
		super();
	}

	public AddCustomerDTO(String username, String password, String firstName, String lastName, String email) {

		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;

	}

	public String getUsername() {
		return username;
	}

	public String getPassword() {
		return password;
	}

	public String getFirstName() {
		return firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public int hashCode() {
		return Objects.hash(email, firstName, lastName, password, username);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AddCustomerDTO other = (AddCustomerDTO) obj;
		return Objects.equals(email, other.email) && Objects.equals(firstName, other.firstName)
				&& Objects.equals(lastName, other.lastName) && Objects.equals(password, other.password)
				&& Objects.equals(username, other.username);
	}

	@Override
	public String toString() {
		return "AddCustomerDTO [username=" + username + ", password=" + password + ", firstName=" + firstName
				+ ", lastName=" + lastName + ", email=" + email + "]";
	}




}// END Class
